"""
FeedScan - bootstrap model training on SYNTHETIC data.

Purpose: validate the full ML pipeline (data -> features -> train -> evaluate ->
export -> in-app inference). The data is generated from expected sensor patterns,
NOT measured from real feed. Retrain on real, lab-referenced samples once the
hardware exists. Accuracy figures printed here describe synthetic data only.

Run:  python ml/train_model.py
Out:  src/model/rfModelData.ts , ml/metrics.json
"""
import json
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

CLASSES = ["GOOD", "CHECK", "ACTION_REQUIRED"]
SPECTRAL = ["f1_415nm", "f2_445nm", "f3_480nm", "f4_515nm", "f5_555nm", "f6_590nm",
            "f7_630nm", "f8_680nm", "clear", "nir"]
FEATURES = SPECTRAL + ["moisture_pct", "temperature_c", "ph", "is_silage",
                       "blue_green_ratio", "nir_clear_ratio"]

# Base spectra [F1..F8, Clear, NIR]; first five match the app's simulator.
SPEC = {
    "good_feed":       [800, 950, 1100, 1350, 1600, 1450, 1200, 1000, 4200, 2800],
    "high_moisture":   [700, 820, 950, 1100, 1350, 1250, 1050, 900, 3600, 2400],
    "suspicious":      [1400, 1500, 1100, 950, 1050, 1150, 1300, 1400, 4600, 3100],
    "good_silage":     [750, 900, 1050, 1280, 1500, 1380, 1150, 950, 3900, 2600],
    "spoiling_silage": [600, 700, 800, 900, 1000, 1100, 1300, 1500, 3200, 2100],
}
# Extra training-only profiles so every class exists for both sample types.
SPEC["wet_moldy_feed"] = [650, 760, 880, 1000, 1150, 1150, 1100, 1000, 3300, 2200]
SPEC["borderline_silage"] = [int((a + b) / 2) for a, b in zip(SPEC["good_silage"], SPEC["spoiling_silage"])]

# name: (label, is_silage, moisture range, temp range, ph range or None)
PROFILES = {
    "good_feed":         ("GOOD",            0, (10, 14), (24, 28), None),
    "high_moisture":     ("CHECK",           0, (19, 24), (26, 30), None),
    "suspicious":        ("CHECK",           0, (12, 16), (25, 29), None),
    "wet_moldy_feed":    ("ACTION_REQUIRED", 0, (25, 32), (28, 34), None),
    "good_silage":       ("GOOD",            1, (55, 65), (18, 22), (3.8, 4.4)),
    "borderline_silage": ("CHECK",           1, (66, 72), (22, 28), (4.6, 5.0)),
    "spoiling_silage":   ("ACTION_REQUIRED", 1, (73, 80), (28, 35), (5.3, 7.0)),
}

def make_dataset(n_per_class, seed, noise):
    rng = np.random.default_rng(seed)
    X, y = [], []
    for name, (label, silage, mo, te, ph) in PROFILES.items():
        base = np.array(SPEC[name], dtype=float)
        for _ in range(n_per_class):
            spec = base * rng.uniform(1 - noise, 1 + noise, size=len(base))
            moisture = rng.uniform(*mo)
            temp = rng.uniform(*te)
            phv = rng.uniform(*ph) if ph else 0.0
            f = dict(zip(SPECTRAL, spec))
            row = list(spec) + [moisture, temp, phv, silage,
                                (f["f1_415nm"] + f["f2_445nm"]) / max(1, f["f5_555nm"] + f["f6_590nm"]),
                                f["nir"] / max(1, f["clear"])]
            X.append(row); y.append(CLASSES.index(label))
    return np.array(X), np.array(y)

# Train with +/-10% noise (the app simulator's noise); test on an independent seed
# with heavier +/-18% noise.
Xtr, ytr = make_dataset(600, seed=1, noise=0.10)
Xte, yte = make_dataset(300, seed=2, noise=0.18)

rf = RandomForestClassifier(n_estimators=30, max_depth=6, min_samples_leaf=5,
                            random_state=42).fit(Xtr, ytr)
pred = rf.predict(Xte)
acc = float(accuracy_score(yte, pred))
cm = confusion_matrix(yte, pred).tolist()
print(f"Synthetic held-out accuracy: {acc:.3f}")
print("Confusion matrix (rows=true, cols=pred):", CLASSES); print(np.array(cm))

def tree_to_dict(t):
    tr = t.tree_
    val = tr.value[:, 0, :]
    val = val / val.sum(axis=1, keepdims=True)
    return {
        "f": [int(x) for x in tr.feature],
        "t": [round(float(x), 4) for x in tr.threshold],
        "l": [int(x) for x in tr.children_left],
        "r": [int(x) for x in tr.children_right],
        "v": [[round(float(p), 4) for p in row] for row in val],
    }

trees = [tree_to_dict(e) for e in rf.estimators_]
ts = (
    "/* AUTO-GENERATED by ml/train_model.py - do not edit.\n"
    " * Random Forest trained on SYNTHETIC bootstrap data (not real measurements). */\n"
    f"export const RF_CLASSES = {json.dumps(CLASSES)} as const;\n"
    f"export const RF_FEATURES = {json.dumps(FEATURES)} as const;\n"
    f"export const RF_SYNTHETIC_ACCURACY = {round(acc, 3)};\n"
    "export interface RfTree { f: number[]; t: number[]; l: number[]; r: number[]; v: number[][]; }\n"
    f"export const RF_TREES: RfTree[] = {json.dumps(trees, separators=(',', ':'))};\n"
)
open("src/model/rfModelData.ts", "w").write(ts)
json.dump({"synthetic_holdout_accuracy": acc, "classes": CLASSES, "confusion_matrix": cm,
           "n_train": int(len(ytr)), "n_test": int(len(yte)), "n_trees": 30, "max_depth": 6,
           "features": FEATURES,
           "note": "Synthetic data only. Not a measure of real-world accuracy."},
          open("ml/metrics.json", "w"), indent=2)
# Reference predictions for verifying the TypeScript port
Xchk, _ = make_dataset(20, seed=3, noise=0.12)
json.dump({"X": Xchk.tolist(), "proba": rf.predict_proba(Xchk).tolist()}, open("ml/ts_check.json", "w"))
print("Wrote src/model/rfModelData.ts")
